-run_mode=true
-log_file=/im/logs/message_server.log
-log_level=0
-registry_host=http://10.2.0.10:2379
-base_service=/service
-instance_name=/message_service/instance
-access_host=10.2.0.10:9006
-listen_port=9006
-rpc_timeout=-1
-rpc_threads=1
-mysql_host=10.2.0.10
-mysql_port=0
-mysql_db=zhutian_im
-mysql_user=root
-mysql_passwd=123456
-mysql_cset=utf8
-mysql_pool_count=4
-es_host=http://10.2.0.10:9200/
-file_service=/service/file_service
-user_service=/service/user_service
-mq_user=root
-mq_passwd=123456
-mq_host=10.2.0.10:5672
-mq_msg_exchange=msg_exchange
-mq_msg_queue=msg_queue
-mq_msg_binding_key=msg_queue